

services:
  mysql-container:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Set the root password
      MYSQL_DATABASE: tpFoyer17  # Create the tpFoyer17 database
    ports:
      - "3306:3306"  # Expose MySQL port
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL data

  springboot-container:
    image: mradeya/tpfoyer:2.4 # Use the custom Docker image 'mradeya/tpfoyer'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/tpFoyer17  # Database connection URL
      SPRING_DATASOURCE_USERNAME: root  # Root user for connection
      SPRING_DATASOURCE_PASSWORD: rootpassword  # Root password
    ports:
      - "8082:8082"  # Expose Spring Boot application port
    depends_on:
      - mysql-container  # Wait for MySQL to start before Spring Boot

volumes:
  mysql_data:  # Persistent volume for MySQL



