

version: '3.8'

services:
  mysql-container:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Définir le mot de passe du root
      MYSQL_DATABASE: tpFoyer17  # Créer la base de données tpFoyer17
    ports:
      - "3306:3306"  # Exposer le port MySQL
    volumes:
      - mysql_data:/var/lib/mysql  # Persistance des données

  springboot-container:
    image: aminelahmer1/devops2024
    build:
      context: .  # Utiliser le Dockerfile dans le répertoire actuel
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/tpFoyer17  # URL de connexion à la base de données
      SPRING_DATASOURCE_USERNAME: root  # Utilisateur root pour la connexion
      SPRING_DATASOURCE_PASSWORD: rootpassword  # Mot de passe du root
    ports:
      - "8082:8081"  # Exposer le port Spring Boot
    depends_on:
      - mysql-container  # Attendre que MySQL démarre avant Spring Boot

volumes:
  mysql_data:  # Volume persistant pour MySQL
