version: '3.8'

services:
  mysql-container:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Définir le mot de passe du root
      MYSQL_DATABASE: tpFoyer17  # Créer la base de données tpFoyer17
    ports:
      - "3306:3306"  # Exposer le port MySQL
    volumes:
      - mysql_data:/var/lib/mysql  # Persistance des données

  springboot-container:
    build:
      context: .  # Utiliser le Dockerfile dans le répertoire actuel
      dockerfile: Dockerfile
    image:  amine_lahmer-springboot-container
    restart: on-failure
    ports:
      - "8082:8082"  # Exposer le port Spring Boot
    depends_on:
      - mysql-container  # Attendre que MySQL démarre avant Spring Boot
    tty: true
volumes:
  db:  # Volume persistant pour MySQL
