version: '3.8'

services:
  # Service pour la base de données MySQL
  mysql-container:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword          # Mot de passe root pour MySQL
      MYSQL_DATABASE: tpFoyer17                 # Base de données à créer
      MYSQL_USER: root                          # Utilisateur MySQL
      MYSQL_PASSWORD: rootpassword              # Mot de passe pour l'utilisateur root
    ports:
      - "3306:3306"                             # Mapping du port pour MySQL
    volumes:
      - mysql_data:/var/lib/mysql               # Volume persistant pour les données MySQL

  # Service pour l'application Spring Boot
  springboot-container:
    build:
      context: .                                # Contexte du build (répertoire actuel)
      dockerfile: Dockerfile                    # Fichier Dockerfile à utiliser
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/tpFoyer17  # URL de connexion à MySQL
      SPRING_DATASOURCE_USERNAME: root                                 # Utilisateur de la base de données
      SPRING_DATASOURCE_PASSWORD: rootpassword                         # Mot de passe de la base de données
    ports:
      - "8082:8082"
      # Mapping du port pour l'application Spring Boot
    depends_on:
      - mysql-container                        # Assure que mysql-container est lancé avant springboot-container

# Volumes persistants pour MySQL
volumes:
  mysql_data:
